# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: project cicd flow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sukyu0919/nike
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: stop skrevolve.org:8080 api server
      run: docker stop sukyu0919/nike
    
    - name: remove docker image sukyu0919/nike
      run: docker rmi nike sukyu0919/nike

    - name: pull docker latest image sukyu0919/nike
      run: docker pull sukyu0919/nike

    - name: restart the sukyu0919/nike container
      run: docker run -d --name nike -p 8080:8080 sukyu0919/nike
