name: CI/CD Docker Hub workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sukyu0919/nike_apiserver
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    name: Deploy
    uses: appleboy/ssh-action@master
    with:
      host: ec2-15-164-219-31.ap-northeast-2.compute.amazonaws.com
      username: ${{ secrets.AWS_USERNAME }}
      password: ${{ secrets.AWS_PASSWORD }}
      envs: GITHUB_SHA
      script: |
        docker stop nike-apiserver
        docker rm -fv nike-apiserver
        docker rmi sukyu0919/nike_apiserver
        docker pull sukyu0919/nike_apiserver:${GITHUB_SHA::7}
        docker tag sukyu0919/nike_apiserver:${GITHUB_SHA::7} nike_apiserver
        docker run -d --name nike-apiserver -p 8080:8080 sukyu0919/nike_apiserver          
